import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, email, phone, subject, message } = body;

    if (!name || !email || !message) {
      return NextResponse.json(
        { error: 'Name, email, and message are required.' },
        { status: 400 }
      );
    }

    // Basic email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: 'Please enter a valid email address.' },
        { status: 400 }
      );
    }

    const apiKey = process.env.RESEND_API_KEY;
    const toEmail = process.env.CONTACT_EMAIL_TO || 'matrimony@flugelsoft.com';

    if (!apiKey) {
      console.error('RESEND_API_KEY environment variable is not configured');
      return NextResponse.json(
        { error: 'Email service configuration error.' },
        { status: 500 }
      );
    }

    const safeSubject = subject || 'General Inquiry';
    const escapedName = String(name).replace(/[<>&"]/g, '');
    const escapedEmail = String(email).replace(/[<>&"]/g, '');
    const escapedPhone = phone ? String(phone).replace(/[<>&"]/g, '') : '';
    const escapedMessage = String(message).replace(/[<>&"]/g, '');

    const resendResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'Matrimony OS <onboarding@resend.dev>',
        to: [toEmail],
        reply_to: email,
        subject: `[Matrimony OS] ${safeSubject} from ${escapedName}`,
        html: `
          <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 16px; background-color: #ffffff;">
            <div style="border-bottom: 2px solid #f43f5e; padding-bottom: 12px; margin-bottom: 20px;">
              <h2 style="color: #be123c; margin: 0; font-size: 20px; font-weight: 800;">New Contact Form Message</h2>
              <p style="margin: 4px 0 0 0; color: #64748b; font-size: 13px;">Matrimony OS Platform Inquiry</p>
            </div>
            
            <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px;">
              <tr>
                <td style="padding: 8px 0; color: #64748b; font-weight: 600; width: 110px;">From:</td>
                <td style="padding: 8px 0; color: #0f172a; font-weight: bold;">${escapedName}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; color: #64748b; font-weight: 600;">Email:</td>
                <td style="padding: 8px 0; color: #0f172a;"><a href="mailto:${escapedEmail}" style="color: #be123c; text-decoration: none;">${escapedEmail}</a></td>
              </tr>
              ${escapedPhone ? `
              <tr>
                <td style="padding: 8px 0; color: #64748b; font-weight: 600;">Phone:</td>
                <td style="padding: 8px 0; color: #0f172a;">${escapedPhone}</td>
              </tr>` : ''}
              <tr>
                <td style="padding: 8px 0; color: #64748b; font-weight: 600;">Subject:</td>
                <td style="padding: 8px 0; color: #0f172a; font-weight: bold;">${safeSubject}</td>
              </tr>
            </table>

            <div style="background-color: #fff1f2; border-left: 4px solid #f43f5e; padding: 16px; border-radius: 8px; margin-bottom: 20px;">
              <div style="font-size: 12px; font-weight: 700; color: #be123c; text-transform: uppercase; margin-bottom: 6px;">Message Content:</div>
              <p style="margin: 0; color: #334155; font-size: 14px; line-height: 1.6; white-space: pre-wrap;">${escapedMessage}</p>
            </div>

            <div style="border-top: 1px solid #f1f5f9; padding-top: 16px; font-size: 12px; color: #94a3b8; text-align: center;">
              This notification was generated by the Matrimony OS Contact Form.
            </div>
          </div>
        `,
      }),
    });

    if (!resendResponse.ok) {
      const errorText = await resendResponse.text();
      console.error('Email delivery error:', errorText);
      return NextResponse.json(
        { error: 'Failed to send message. Please try again shortly.' },
        { status: 500 }
      );
    }

    const result = await resendResponse.json();
    return NextResponse.json({ success: true, id: result.id });
  } catch (error: any) {
    console.error('Contact route handler error:', error);
    return NextResponse.json(
      { error: 'Internal server error occurred.' },
      { status: 500 }
    );
  }
}
